defaults:
    - agent: sac

env: window-open-v2-goal-observable
random_hand_init: false

# this needs to be specified manually
experiment: mw-dc

num_train_steps: 1e6 # 1 million training steps
replay_buffer_capacity: ${num_train_steps}
max_episode_steps: 500
num_seed_steps: 5000

eval_frequency: 10000
save_every_steps: 10000
num_eval_episodes: 10

device: cuda

# logger
log_frequency: 10000
log_save_tb: false
log_to_wandb: false

# video recorder
save_video: true

seed: 0
experiment_dir: /home/anthony/dt_adapters/pytorch_sac/outputs/
checkpoint_path: /home/anthony/dt_adapters/pytorch_sac/outputs/mw-dc/${env}/models/step_50000.pt

# for eval
num_rollouts: 10