defaults:
    - agent: sac

env: pick-place-v2
random_hand_init: false

# this needs to be specified manually
experiment: mw-dc-5M-t2

num_train_steps: 5e6 # 5 million training steps
replay_buffer_capacity: ${num_train_steps}
max_episode_steps: 500
num_seed_steps: 5000

eval_frequency: 200000
save_every_steps: 200000
num_eval_episodes: 10

device: cuda

# logger
log_frequency: 10000
log_save_tb: false

# video recorder
save_video: true

log_to_wandb: true

seed: 0

experiment_dir: /home/anthony/dt_adapters/pytorch_sac/outputs/
restore_from_checkpoint: false 

# hydra configuration
# hydra:
#     name: ${env}
#     run:
#         dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_${experiment}