defaults:
  - model: 
    - base
    - decision_transformer
  - data: 
    - base 
    - mw_blocks_only
  - general: base

general:
  load_from_ckpt: True
  stage: finetuning
  freeze_backbone: True

model:
  use_adapters: True