num_demos_per_env: 100
domain: metaworld
data_dir: /data/anthony/dt_adapters/data/metaworld_data/
data_file: trajectories_all_with_images_${demos_per_env}.hdf5
image_height: 256
image_width: 256
max_episode_length: 500
tasks: box-close-v2
vision_backbone: r3m
image_keys: ["corner", "corner2", "topview"]