defaults:
  - model: 
    - base
    - decision_transformer
  - data: 
    - base 
    - mw_blocks_only
  - general: base

# extra eval config
num_processes: 0
filter_envs_by_obj: block
metrics_file: /data/anthony/dt_adapters/metrics_10.csv

general:
  exp_name: zero_shot_eval

  online_training: True
  model_ckpt_dir: /data/anthony/dt_adapters/outputs/
  load_from_ckpt: True
  obj_randomization: False
  log_outputs: False

  stage: eval
  mode: eval
  tasks_to_evaluate:
    - ReachTarget