defaults:
  - model: 
    - base
    - decision_transformer
  - data: 
    - base 
    - mw_blocks_only
  - general: base

general:
  load_from_ckpt: True
  num_eval_rollouts: 10
  train_on_offline_data: True
  obj_randomization: True
  use_adapters: True  
  stage: finetuning