# base configuration for training 
defaults:
  - model: 
    - base
    - decision_transformer
  - data: 
    - base 
    - mw_blocks_only
  - general: base

general:
  online_training: False                          
  train_on_offline_data: True
  stage: pretraining

model:
  use_adapters: False

data:
  obj_randomization: True