hidden_size: 768
act_dim: 4
pos_hand: 3
obs_obj_max_len: 14
gripper_distance_apart: 1
goal_pos: 3
state_dim: 39
num_layers: 3

emb_state_separate: True

stochastic: False
use_entropy: False
target_entropy: False
predict_return_dist: False