hidden_size: 768
max_length: ${data.context_len}
max_ep_len: 500
component_hidden_size: 256
action_tanh: True

log_std_min: -20
log_std_max: 2
remove_pos_embs: False
stochastic_tanh: False
approximate_entropy_samples: 1000

# for predicting returns
predict_return_dist: False
max_return: 500
bin_width: 5
num_return_samples: 250

model_cls: decision_transformer

gpt2:
  n_layer: 4
  n_head: 4
  dropout: 0.1
  n_embd: ${model.hidden_size}