multiprocessing: True 
debug: False 
num_processes: 10
log_to_wandb: False
demos_per_env: 10
# filter_envs_by_obj: 
data_dir: /data/anthony/dt_adapters/data/
data_file: trajectories_no_goal_with_images_${demos_per_env}.hdf5"