defaults:
  - model: decision_transformer
  - data: metaworld
  - general: base

general:
  online_training: True
  model_ckpt_dir: /data/anthony/dt_adapters/outputs/
  load_from_ckpt: True
  env_name: pick-place-wall-v2
  num_online_rollouts: 5
  num_eval_rollouts: 10
  train_on_offline_data: False
  num_warmup_rollouts: 10
  target_return: 4000
  scale: 1000
  obj_randomization: False

  use_adapters: True