save_every: 10
eval_every: 10
num_steps_per_epoch: 50
skip_first_eval: False
num_epochs: 100
batch_size: 64
data_dir: /home/anthony/dt_adapters/data/
data_file: trajectories_block_only_no_images_10.hdf5
seed: 0
num_data_workers: 1
output_dir: /home/anthony/dt_adapters/outputs
exp_name: test_train_dt
log_to_wandb: False

lr: 1e-4
weight_decay: 1e-4
alpha_lr: 1e-4
alpha_weight_decay: 1e-4

online_training: False 
model_ckpt_dir: ""
use_adapters: False
num_online_rollouts: 1


data: 
  context_len: 50
  state_dim: 39
  act_dim: 4
  max_ep_len: 500
  data_dir: ${data_dir}
  data_file: ${data_file}

model:
  hidden_size: 768
  n_layer: 4
  n_head: 4
  dropout: 0.1
  max_length: ${data.context_len}
  act_dim: 4
  pos_hand: 3
  obs_obj_max_len: 14
  gripper_distance_apart: 1
  goal_pos: 3
  state_dim: 39
  component_hidden_size: 256
  action_tanh: True

  stochastic: True 
  log_std_min: -20
  log_std_max: 2
  remove_pos_embs: False
  stochastic_tanh: True
  approximate_entropy_samples: 1000
  use_entropy: False
  target_entropy: False

