defaults:
  - model: 
    - base
    - decision_transformer
  - data: 
    - base 
    - mw_blocks_only
  - general: base

general:
  online_training: False 
  train_on_offline_data: True
  model_ckpt_dir: ""
  use_adapters: False
  stage: pretraining