defaults:
  - model: decision_transformer
  - data: metaworld
  - general: base

general:
  online_training: False 
  train_on_offline_data: True
  model_ckpt_dir: ""
  use_adapters: False
  num_online_rollouts: 1
  stage: pretraining