save_every: 10
eval_every: 10
num_steps_per_iter: 200
num_epochs: 100
batch_size: 64
data_dir: /home/anthony/dt_adapters/data/
data_file: trajectories_block_only_no_images_10.hdf5
seed: 0
num_data_workers: 1
output_dir: /home/anthony/dt_adapters/outputs
exp_name: test_train_dt
log_to_wandb: False

lr: 1e-4
weight_decay: 1e-4

data: 
  context_len: 50
  state_dim: 39
  act_dim: 4
  max_ep_len: 500
  data_dir: ${data_dir}
  data_file: ${data_file}

model:
  hidden_size: 768
  n_layer: 4
  n_head: 4
  dropout: 0.1
  max_length: ${data.context_len}
  act_dim: 4
  pos_hand: 3
  obs_obj_max_len: 14
  gripper_distance_apart: 1
  goal_pos: 3
  state_dim: 39
  component_hidden_size: 256
  action_tanh: True

  stochastic: True 
  log_std_min: -20
  log_std_max: 2
  remove_pos_embs: False
  stochastic_tanh: False
  approximate_entropy_samples: 1000
  use_entropy: True 
  target_entropy: True

alpha_lr: 1e-4
alpha_weight_decay: 1e-4


# adapter configs
use_adapters: True
model_ckpt_dir: /home/anthony/dt_adapters/outputs/train_dt_offline_dataset_size/seed=0,data.context_len=50,model.n_layer=4,model.n_head=4,data_file=trajectories_block_only_no_images_10.hdf5,-107777
adapter_task_name: bin-picking-v2 # this should be the task name
adapter:
  config: pfeiffer+inv
  nonlinearity: none 
  reduction_factor: none